export SECRET="CastingAgencyAPI"
export ASSISTANT_TOKEN=""
export DIRECTOR_TOKEN=""
export PRODUCER_TOKEN=""
export AUTH0_DOMAIN="hassanlatif.uk.auth0.com"
export API_AUDIENCE="CastingAgencyAPI"
export ALGORITHMS=['RS256']
export FLASK_APP=flaskr
export FLASK_ENV=development
export TEST_DATABASE_URI="postgres://localhost:5432/casting_agency_test"
export DATABASE_URI="postgres://localhost:5432/casting_agency"
export NEW_VAR="Testing export"